apiVersion: apps/v1
kind: Deployment
metadata:
  name: manage_data_api
  labels:
    app: manage_data_api
spec:
  replicas: 2
  
  selector:
    matchLabels:
      app: manage_data_api
  
  template:
    metadata:
      labels:
        app: manage_data_api
    spec:
      containers:
      - name: manage_data_api
        image: israelyarbloom/manage_data_api:v1
        
        ports:
        - containerPort: 8000

        env:
        - name: HOST
          value: "mysql-svc"
        - name: PASSWORD
          value: "password"
        - name: ROOT
          value: "root"
        - name: DB_NAME
          value: weapons_db